### ISSUE TITLE
Provide a LICENSE file

### ISSUE THREAD

**Issue by brean** [cram2/pycram#11]
There is no information about the license that this used to publish this code.
Note that you are infringing the macropy license by redistributing its code without its license!

**Comment by gaya-** [comment]
Indeed. Macropy has the MIT licence so they wouldn't mind much but we do need to find a better solution for this. Probably make a fork of macropy with our commits and link to that. @Tigul

**Comment by Tigul** [comment]
With PR #12 macropy was seperated into it's own repo and is now included via a submodule. The new repo has now the proper LICENSE file.
